### ISSUE TITLE
PHP 7.0 Support

### ISSUE THREAD

**Issue by bassrock** [mihai-stancu/doctrine-types-extra#1]
Currently the version param of php in the composer file limits you to use php 5.5.9 it would be great to make it >=5.5.9 to allow newer php versions.

**Comment by mihai-stancu** [comment]
@bassrock I'm sorry I didn't see this message -- it's weird that I didn't get an email about it either.

I fixed it now. And I also removed the `~2@dev|~3@dev` references to symfony components since symfony 3 has been released.
